/*
 Navicat Premium Data Transfer

 Source Server         : mysql
 Source Server Type    : MySQL
 Source Server Version : 80031 (8.0.31)
 Source Host           : localhost:3306
 Source Schema         : task

 Target Server Type    : MySQL
 Target Server Version : 80031 (8.0.31)
 File Encoding         : 65001

 Date: 13/03/2023 09:30:05
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for phone
-- ----------------------------
DROP TABLE IF EXISTS `phone`;
CREATE TABLE `phone`  (
  `id` int NOT NULL AUTO_INCREMENT,
  `content` varchar(2000) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL,
  `image` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL,
  `price` double NOT NULL,
  `status` int NULL DEFAULT NULL,
  `title` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 27 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of phone
-- ----------------------------
INSERT INTO `phone` VALUES (7, '\r\nDesigned by Apple to complement iPhone 14 Pro, the Leather Case with MagSafe is a delightful way to give your iPhone extra protection while adding style.\r\n\r\nMade from specially tanned and finished leather, the outside feels soft to the touch and develops a natural patina over time. The case quickly snaps into place and fits snugly over your iPhone without adding bulk.\r\n\r\nWith built-in magnets that align perfectly with iPhone 14 Pro, the case offers a magical attach and detach experience, every time. The perfectly aligned magnets make wireless charging faster and easier than ever before. And when it’s time to charge, just leave the case on your iPhone and snap on your MagSafe charger, or place it on your Qi-certified charger.\r\n\r\nLike every Apple-designed case, it undergoes thousands of hours of testing throughout the design and manufacturing process. So not only does it look great, it’s built to protect your iPhone from scratches and drops.\r\n\r\nThis case is made with high-quality, supple leather to protect your iPhone. Leather is a natural material and like a fine leather belt, it may show creases, marks or a patina over time. Interaction with MagSafe accessories will leave slight imprints. If you are concerned about this, we suggest you use an iPhone 14 Pro Silicone Case or Clear Case.', '../images/Sunglow.jfif', 79, 1, 'iPhone 14 Pro Max Silicone Case with MagSafe — Sunglow');
INSERT INTO `phone` VALUES (8, '\r\nDesigned by Apple to complement iPhone 14 Pro, the Leather Case with MagSafe is a delightful way to give your iPhone extra protection while adding style.\r\n\r\nMade from specially tanned and finished leather, the outside feels soft to the touch and develops a natural patina over time. The case quickly snaps into place and fits snugly over your iPhone without adding bulk.\r\n\r\nWith built-in magnets that align perfectly with iPhone 14 Pro, the case offers a magical attach and detach experience, every time. The perfectly aligned magnets make wireless charging faster and easier than ever before. And when it’s time to charge, just leave the case on your iPhone and snap on your MagSafe charger, or place it on your Qi-certified charger.\r\n\r\nLike every Apple-designed case, it undergoes thousands of hours of testing throughout the design and manufacturing process. So not only does it look great, it’s built to protect your iPhone from scratches and drops.\r\n\r\nThis case is made with high-quality, supple leather to protect your iPhone. Leather is a natural material and like a fine leather belt, it may show creases, marks or a patina over time. Interaction with MagSafe accessories will leave slight imprints. If you are concerned about this, we suggest you use an iPhone 14 Pro Silicone Case or Clear Case.', '../images/Succulent.jfif', 79, 1, 'iPhone 14 Pro Max Silicone Case with MagSafe — Succulent');
INSERT INTO `phone` VALUES (9, '\r\nDesigned by Apple to complement iPhone 14 Pro, the Leather Case with MagSafe is a delightful way to give your iPhone extra protection while adding style.\r\n\r\nMade from specially tanned and finished leather, the outside feels soft to the touch and develops a natural patina over time. The case quickly snaps into place and fits snugly over your iPhone without adding bulk.\r\n\r\nWith built-in magnets that align perfectly with iPhone 14 Pro, the case offers a magical attach and detach experience, every time. The perfectly aligned magnets make wireless charging faster and easier than ever before. And when it’s time to charge, just leave the case on your iPhone and snap on your MagSafe charger, or place it on your Qi-certified charger.\r\n\r\nLike every Apple-designed case, it undergoes thousands of hours of testing throughout the design and manufacturing process. So not only does it look great, it’s built to protect your iPhone from scratches and drops.\r\n\r\nThis case is made with high-quality, supple leather to protect your iPhone. Leather is a natural material and like a fine leather belt, it may show creases, marks or a patina over time. Interaction with MagSafe accessories will leave slight imprints. If you are concerned about this, we suggest you use an iPhone 14 Pro Silicone Case or Clear Case.', '../images/Lilac.jfif', 79, 1, 'iPhone 14 Pro Max Silicone Case with MagSafe — Lilac');
INSERT INTO `phone` VALUES (10, '\r\nDesigned by Apple to complement iPhone 14 Pro, the Leather Case with MagSafe is a delightful way to give your iPhone extra protection while adding style.\r\n\r\nMade from specially tanned and finished leather, the outside feels soft to the touch and develops a natural patina over time. The case quickly snaps into place and fits snugly over your iPhone without adding bulk.\r\n\r\nWith built-in magnets that align perfectly with iPhone 14 Pro, the case offers a magical attach and detach experience, every time. The perfectly aligned magnets make wireless charging faster and easier than ever before. And when it’s time to charge, just leave the case on your iPhone and snap on your MagSafe charger, or place it on your Qi-certified charger.\r\n\r\nLike every Apple-designed case, it undergoes thousands of hours of testing throughout the design and manufacturing process. So not only does it look great, it’s built to protect your iPhone from scratches and drops.\r\n\r\nThis case is made with high-quality, supple leather to protect your iPhone. Leather is a natural material and like a fine leather belt, it may show creases, marks or a patina over time. Interaction with MagSafe accessories will leave slight imprints. If you are concerned about this, we suggest you use an iPhone 14 Pro Silicone Case or Clear Case.', '../images/Chalk Pink.jfif', 79, 1, 'iPhone 14 Pro Max Silicone Case with MagSafe — Chalk Pink');
INSERT INTO `phone` VALUES (15, 'The Smart Folio for iPad is thin and light, and offers front and back protection for your device. It automatically wakes your iPad when opened and sends it to sleep when closed. The Smart Folio attaches magnetically, and you can easily fold it into different positions to create a stand for reading, viewing, typing or making FaceTime calls.', '../images/White Case.jfif', 129, 2, 'Smart Folio for iPad (10th generation) — White');
INSERT INTO `phone` VALUES (16, 'The Smart Folio for iPad is thin and light, and offers front and back protection for your device. It automatically wakes your iPad when opened and sends it to sleep when closed. The Smart Folio attaches magnetically, and you can easily fold it into different positions to create a stand for reading, viewing, typing or making FaceTime calls.', '../images/Blue Case.jfif', 129, 2, 'Smart Folio for iPad (10th generation) — Sky');
INSERT INTO `phone` VALUES (17, 'The Smart Folio for iPad is thin and light, and offers front and back protection for your device. It automatically wakes your iPad when opened and sends it to sleep when closed. The Smart Folio attaches magnetically, and you can easily fold it into different positions to create a stand for reading, viewing, typing or making FaceTime calls.', '../images/Red Case.jfif', 129, 2, 'Smart Folio for iPad (10th generation) — Red');
INSERT INTO `phone` VALUES (18, 'The Smart Folio for iPad is thin and light, and offers front and back protection for your device. It automatically wakes your iPad when opened and sends it to sleep when closed. The Smart Folio attaches magnetically, and you can easily fold it into different positions to create a stand for reading, viewing, typing or making FaceTime calls.', '../images/Yellow Case.jfif', 129, 2, 'Smart Folio for iPad (10th generation) — Yellow');
INSERT INTO `phone` VALUES (19, '\r\nMagic Keyboard is available with Touch ID, providing fast, easy and secure authentication for logins and purchases.\r\n\r\nMagic Keyboard with Touch ID and Numeric Keypad delivers a remarkably comfortable and precise typing experience. It features an extended layout, with document navigation controls for quick scrolling and full-sized arrow keys, which are great for gaming. The numeric keypad is also ideal for spreadsheets and finance applications. It’s wireless and features a rechargeable battery that will power your keyboard for about a month or more between charges.¹ It pairs automatically with your Mac, so you can get to work straight away. And it includes a woven USB-C to Lightning Cable that lets you pair and charge by connecting to a USB-C port on your Mac.', '../images/White Keyboard.jfif', 279, 3, 'Magic Keyboard White Keys');
INSERT INTO `phone` VALUES (20, '\r\nMagic Keyboard is available with Touch ID, providing fast, easy and secure authentication for logins and purchases.\r\n\r\nMagic Keyboard with Touch ID and Numeric Keypad delivers a remarkably comfortable and precise typing experience. It features an extended layout, with document navigation controls for quick scrolling and full-sized arrow keys, which are great for gaming. The numeric keypad is also ideal for spreadsheets and finance applications. It’s wireless and features a rechargeable battery that will power your keyboard for about a month or more between charges.¹ It pairs automatically with your Mac, so you can get to work straight away. And it includes a woven USB-C to Lightning Cable that lets you pair and charge by connecting to a USB-C port on your Mac.', '../images/Black Keyboard.jfif', 279, 3, 'Magic Keyboard Black Keys');
INSERT INTO `phone` VALUES (21, 'Magic Mouse is wireless and rechargeable, with an optimised foot design that lets it glide smoothly across your desk. The Multi-Touch surface allows you to perform simple gestures such as swiping between web pages and scrolling through documents.\r\n\r\nThe rechargeable battery will power your Magic Mouse for about a month or more between charges. It’s ready to go straight out of the box and pairs automatically with your Mac, and it includes a woven USB-C to Lightning Cable that lets you pair and charge by connecting to a USB-C port on your Mac.', '../images/White Mouse.jfif', 139, 3, 'Magic Mouse — White Multi-Touch Surface');
INSERT INTO `phone` VALUES (22, 'Magic Mouse is wireless and rechargeable, with an optimised foot design that lets it glide smoothly across your desk. The Multi-Touch surface allows you to perform simple gestures such as swiping between web pages and scrolling through documents.\r\n\r\nThe rechargeable battery will power your Magic Mouse for about a month or more between charges. It’s ready to go straight out of the box and pairs automatically with your Mac, and it includes a woven USB-C to Lightning Cable that lets you pair and charge by connecting to a USB-C port on your Mac.', '../images/Black Mouse.jfif', 139, 3, 'Magic Mouse — Black Multi-Touch Surface');
INSERT INTO `phone` VALUES (23, 'Made from a custom-developed high-performance fluoroelastomer, the Sport Band is durable and strong, yet surprisingly soft. The smooth, dense material drapes elegantly across your wrist and feels comfortable next to your skin. An innovative pin-and-tuck closure ensures a clean fit.', '../images/Band Elderberry.jfif', 69, 4, '45-mm Elderberry Sport Band\r\n45-mm Elderberry Sport Band\r\n45-mm Elderberry Sport Band');
INSERT INTO `phone` VALUES (24, 'Made from a custom-developed high-performance fluoroelastomer, the Sport Band is durable and strong, yet surprisingly soft. The smooth, dense material drapes elegantly across your wrist and feels comfortable next to your skin. An innovative pin-and-tuck closure ensures a clean fit.', '../images/Band Regular.jfif', 69, 4, '45-mm Midnight Sport Band — Regular');
INSERT INTO `phone` VALUES (25, 'Made from a custom-developed high-performance fluoroelastomer, the Sport Band is durable and strong, yet surprisingly soft. The smooth, dense material drapes elegantly across your wrist and feels comfortable next to your skin. An innovative pin-and-tuck closure ensures a clean fit.', '../images/Band Succulent.jfif', 69, 4, '45-mm Succulent Sport Band');
INSERT INTO `phone` VALUES (26, 'Made from a custom-developed high-performance fluoroelastomer, the Sport Band is durable and strong, yet surprisingly soft. The smooth, dense material drapes elegantly across your wrist and feels comfortable next to your skin. An innovative pin-and-tuck closure ensures a clean fit.', '../images/Band White.jfif', 69, 4, '45-mm White Sport Band');

SET FOREIGN_KEY_CHECKS = 1;
