server:
  port: 8081

spring:
  datasource:
    username: root
    password: 1234
    url: jdbc:mysql:///task
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  thymeleaf:
    prefix: classpath:/static/web/
    suffix: .html
    cache: false

  redis:
    port: 6379
    host: localhost

logging:
  level:
    com.example: debug







